# Generated by Django 4.2.17 on 2024-12-28 13:55

import django.core.validators
from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4', 'jpeg', 'png', 'gif']), file_upload.models.validate_file_size])),
                ('filename', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], max_length=5)),
            ],
        ),
    ]
