# Generated by Django 4.2.17 on 2024-12-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='Default_Value', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], default='IMAGE', max_length=5),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(default='jpeg', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(default='Default_Value.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='size',
            field=models.BigIntegerField(default=10000),
        ),
    ]
